language: clojure
lein: lein2
script: lein2 clean && lein2 test
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
  - openjdk6
env:
  - _JAVA_OPTIONS='-Xms64m -Xmx128m -XX:+AggressiveOpts'
deploy:
  provider: heroku
  api_key:
    secure: XlpJUnvjuguKXafPSMsqtn/MI242Ff52PRzVqdzB40WFoq4Eqpmw+Ig3xEjKFYr6ECwBYz10UbJTne4uTBgMYWxUUsLmsKdHhyROdPNc+LK0lBL+202f1BS6muEuKgvIi8gQMpgM2QeiEIT7jcZJAhYVyx8qTWZminORhPjSJYs=
  app: sheltered-dusk-9213
