language: clojure

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - PROJECT_DIR=${TRAVIS_BUILD_DIR}
    - _JAVA_OPTIONS='-Xms64m -Xmx128m -XX:+AggressiveOpts'

before_install : ./travis/before_install.sh
install        : ./travis/install.sh
before_script  : ./travis/before_script.sh
script         : ./travis/script.sh
after_success  : ./travis/after_success.sh
after_failure  : ./travis/after_failure.sh
after_script   : ./travis/after_script.sh

deploy:
  provider  : heroku
  buildpack : clojure
  api_key:
    secure  : Cyvu2Dg/1ydTXin20FFkr6YkyywU2fI+umUytA5yzkG2yCD95lqw7f5YBobGZ4jcKWTQ6vydkqoYpYaj2oSoSbtlHrB7jJQnAXTVHKOdBsEqkx2wJ+OfdfKnatXlbFBAM3NJjiDaZTAin4lDEqcpq7FgxtFF9mekWLTuVMCIH3Q=
  app:
    master : choreo-app
    dev    : sheltered-dusk-9213
  on:
    jdk  : openjdk7
    repo : rubicks/choreo
#    all_branches : true
